export default {
  primary: '#E0B6FF',
  secondary: '',
  white: 'white',
  black: 'black',
  red: 'red',
  darkBlue: 'blue',
  light: 'grey',
  blue: '#0E184D',
  grey: 'grey',
  grey2: '#4F4F4F',
  grey4: '#bdbdbd',
  disabled: '#E0E0E0',
  cyanBlue: '#000F1A',
  almostBlack: '#000C14',
};
